wandb_version: 1

causal_estimators:
  desc: null
  value:
  - sl
  - tl
  - xl
  - dml
  - sparse_dml
  - kernel_dml
  - CausalForestDML
classifiers:
  desc: null
  value:
  - GradientBoostingClassifier()
  - RandomForestClassifier()
  - LogisticRegression()
  - LogisticRegressionCV()
  - MLPClassifier()
  - DecisionTreeClassifier()
  - auto
regressors:
  desc: null
  value:
  - GradientBoostingRegressor()
  - RandomForestRegressor()
  - LinearRegression()
  - ElasticNet()
  - ElasticNetCV()
  - Lasso()
  - LassoLars()
  - Ridge()
  - MLPRegressor()
  - DecisionTreeRegressor()
  - auto
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682038744.358304
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.15.0
      8:
      - 4
      - 5
